# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chap05/Pityna/qt_PitynaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetLog = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLog.setGeometry(QtCore.QRect(5, 0, 340, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidgetLog.setFont(font)
        self.listWidgetLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetLog.setObjectName("listWidgetLog")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(200, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 510, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(5, 540, 680, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.ButtonTalk = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTalk.setGeometry(QtCore.QRect(690, 540, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ButtonTalk.setFont(font)
        self.ButtonTalk.setObjectName("ButtonTalk")
        self.LabelResponce = QtWidgets.QLabel(self.centralwidget)
        self.LabelResponce.setGeometry(QtCore.QRect(350, 300, 500, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelResponce.setFont(font)
        self.LabelResponce.setFrameShape(QtWidgets.QFrame.Box)
        self.LabelResponce.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LabelResponce.setText("")
        self.LabelResponce.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelResponce.setObjectName("LabelResponce")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 0, 500, 300))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/re/img1.gif"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.LineEdit = QtWidgets.QStatusBar(MainWindow)
        self.LineEdit.setObjectName("LineEdit")
        MainWindow.setStatusBar(self.LineEdit)
        self.menuClose = QtWidgets.QAction(MainWindow)
        self.menuClose.setObjectName("menuClose")
        self.menu.addAction(self.menuClose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.ButtonTalk.clicked.connect(MainWindow.button_talk_slot) # type: ignore
        self.radioButton_2.clicked.connect(MainWindow.show_responder_name) # type: ignore
        self.radioButton.clicked.connect(MainWindow.hidden_responder_name) # type: ignore
        self.menuClose.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "Responderを非表示"))
        self.radioButton_2.setText(_translate("MainWindow", "Responderを表示"))
        self.ButtonTalk.setText(_translate("MainWindow", "話す"))
        self.menu.setTitle(_translate("MainWindow", "ファイル"))
        self.menuClose.setText(_translate("MainWindow", "閉じる"))
import qt_resource_rc
